/* As per later discussion
Note: Filter should be global not needed on every column instead of this we will have one global filter which will 
--> take column Name and value
--> FilterMode--> "TEXT"
*/
const EC2Instance = [
  {
    column: "name",
    displayLabel: "Instance",
    display: "true",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "guest",
    displayLabel: "Instance",
    display: "true",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "instanceId",
    displayLabel: "Instance ID",
    display: "true",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "tags",
    displayLabel: "Tags",
    displayOrder: 3,
    display: {
      EC2: "true",
      EBS: "true",
      RDS: "true",
      "Load Balancer": "true",
      "S3 Buckers": "true",
      Lambda: "true",
      DynamoDB: "true",
      EFS: "true",
      EKS: "true",
      ECR: "false",
      FSX: "true",
    },
    display: "true",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "type",
    displayLabel: "Type",
    display: "true",
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "zone",
    displayLabel: "Zone",
    display: { EC2: "true", EBS: "true", RDS: "false" },
    displayOrder: 5,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "totalSnapshots",
    displayLabel: "Total Snapshots",
    displayOrder: 7,
    canHide: true,
    display: {
      EC2: "true",
      RDS: "true",
      "Load Balancer": "true",
      "S3 Buckers": "true",
      Lambda: "true",
      DynamoDB: "true",
      EFS: "true",
      EKS: "true",
      ECR: "false",
      FSX: "true",
    },
    sortable: "true",
    filterable: "false",
    filterMode: "none",
    sortOrder: { asc: "true", desc: "true" },
  },

  {
    column: "latestSnapshot",
    displayLabel: "Total Snapshots",
    display: "true",
    displayOrder: 7,
    canHide: true,
  },
  {
    column: "kmsKeyId",
    displayLabel: "Encryption",
    display: true,
    displayOrder: 8,
    canHide: true,
    display: {
      EC2: "true",
      EBS: "true",
      RDS: "true",
      "Load Balancer": "false",
      "S3 Buckers": "false",
      Lambda: "false",
      DynamoDB: "false",
      EFS: "true",
      EKS: "false",
      ECR: "true",
      FSX: "true",
    },
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "backupTypes",
    displayLabel: "Protection Status",
    display: true,
    displayOrder: 9,
    canHide: true,
    sortable: false,
    filterable: false,
    filterMode: "none",
    sortOrder: { asc: "true", desc: "true" },
    display1: {
      EC2: "true",
      EBS: "true",
      RDS: "true",
      "Load Balancer": "true",
      "S3 Buckers": "true",
      Lambda: "true",
      DynamoDB: "true",
      EFS: "false",
      EKS: "true",
      ECR: "true",
      FSX: "false",
    },
  },
  {
    column: "powerScheduled",
    display: "true",
    displayLabel: "PowerManagement Status",
    display: true,
    displayOrder: 10,
    canHide: true,
    display: {
      EC2: "true",
      EBS: "true",
      RDS: "true",
      "Load Balancer": "true",
      "S3 Buckers": "true",
      Lambda: "true",
      DynamoDB: "true",
      EFS: "false",
      EKS: "true",
      ECR: "true",
      FSX: "false",
    },
    sortable: "false",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "state",
    displayName: "Action",
    display: "true",
    displayOrder: 10,
    canHide: true,
    sortable: "false",
    filterable: "false",
    filterMode: "None",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "backups",
    display: "false",
  },
  {
    column: "deleted",
    display: "false",
  },
  {
    column: "amiId",
    display: "false",
  },
  {
    column: "instanceUsage",
    display: "false",
  },
  {
    column: "isclone",
    display: "false",
  },
  {
    column: "marketplaceSubscribed",
    display: "false",
  },
  {
    column: "metrics",
    display: "false",
  },
  {
    column: "privateIPV4Address",
    display: "false",
  },
  {
    column: "recentBackup",
    display: "false",
  },
  {
    column: "rootDevice",
    display: "false",
  },
];
const EBSVolumes = [
  {
    column: "volumeid",
    displayName: "Volume",
    display: "true",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "tags",
    displayLabel: "Tags",
    display: "true",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "deviceName",
    displayName: "Device Name",
    display: true,
    displayOrder: 3,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "zone",
    displayLabel: "Zone",
    display: true,
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "size",
    displayName: "Size",
    display: true,
    displayOrder: 5,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "totalSnapshots",
    displayLabel: "Total Snapshots",
    display: true,
    displayOrder: 6,
    canHide: true,
    sortable: "true",
    filterable: "false",
    filterMode: "none",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "latestSnapshot",
    displayLabel: "Total Snapshots",
    display: "true",
    displayOrder: 6,
    canHide: true,
  },
  {
    column: "latestSnapshotId",
    displayLabel: "Total Snapshots",
    display: "true",
    displayOrder: 6,
    canHide: true,
  },
  {
    column: "kmsKeyId",
    displayLabel: "Encryption",
    display: true,
    displayOrder: 7,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "instanceId",
    displayLabel: "Attachment Info",
    display: true,
    displayOrder: 8,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "backupTypes",
    displayLabel: "Protection Status",
    display: true,
    displayOrder: 9,
    canHide: true,
    sortable: false,
    filterable: false,
    filterMode: "none",
    sortOrder: { asc: "true", desc: "true" },
  },
  { column: "name", display: "false" },
  { column: "region", display: "false" },
  { column: "deleted", display: "false" },
  { column: "hasSecondaryBackups", display: "false" },
  { column: "isclone", display: "false" },
  { column: "snapshotId", display: false },
];
const RDSInstance = [
  {
    column: "awsIdentifier",
    display: "true",
    displayOrder: 1,
    canHide: true,
    displayLabel: "DB Identifier",
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "tagProperties",
    displayLabel: "Tags",
    display: "true",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "instanceProperties[engine]",
    display: "true",
    displayOrder: 3,
    canHide: true,
    displayLabel: "Engine",
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "instanceProperties[multiAZ]",
    display: "true",
    displayOrder: 4,
    canHide: true,
    displayLabel: "Multi-AZ",
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "instanceProperties[dbInstanceStatus]",
    display: "true",
    displayOrder: 5,
    canHide: true,
    displayLabel: "Status",
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "instanceProperties[licenseModel]",
    display: "true",
    displayOrder: 6,
    canHide: true,
    displayLabel: "License",
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "snapshots.snapShotCount",
    display: "true",
    displayOrder: 7,
    canHide: true,
    displayLabel: "Total Snapshots",
    sortable: "true",
    filterable: "false",
    filterMode: "none",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "snapshots.latestSnapshot",
    displayLabel: "Total Snapshots",
    display: "true",
    displayOrder: 7,
    canHide: true,
  },
  {
    column: "instanceProperties[kmsKeyId]",
    display: "true",
    displayOrder: 8,
    canHide: true,
    displayLabel: "Encryption",
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "backupTypes",
    displayLabel: "Protection Status",
    display: true,
    displayOrder: 9,
    canHide: true,
    sortable: false,
    filterable: false,
    filterMode: "none",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "powerStatus",
    display: "true",
    displayOrder: 10,
    canHide: true,
    displayLabel: "PowerManagement Status",
    sortable: "false",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "instanceProperties[dbInstanceStatus]",
    display: "true",
    displayOrder: 11,
    canHide: true,
    displayLabel: "Action",
    sortable: "false",
    filterable: "false",
    filterMode: null,
  },
  {
    column: "region",
    display: "false",
  },

  {
    column: "hasSecondaryBackups",
    display: "false",
  },
  {
    column: "deleted",
    display: "false",
  },
];

const LoadBalancer = [
  {
    column: "loadBalancerName",
    displayLabel: "Name",
    display: "true",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "tags",
    displayLabel: "Tags",
    display: "true",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "metadata.dnsName",
    display: true,
    displayLabel: "DNS",
    displayOrder: 3,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "targetGroupViewModelList",
    displayLabel: "Targets",
    display: true,
    displayOrder: 4,
    canHide: true,
    sortable: "false",
    filterable: "false",
    filterMode: "none",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "metadata.createdTime",
    display: true,
    displayOrder: 5,
    canHide: true,
    displayLabel: "Created On",
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "metadata.code",
    display: true,
    displayOrder: 6,
    canHide: true,
    displayLabel: "State",
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "metadata.vpcId",
    display: true,
    displayLabel: "VPC ID",
    displayOrder: 7,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "type",
    display: "true",
    displayOrder: 8,
    canHide: true,
    displayLabel: "Type",
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "backupTypes",
    displayLabel: "Protection Status",
    display: true,
    displayOrder: 9,
    canHide: true,
    sortable: false,
    filterable: false,
    filterMode: "none",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "route53", //need to discuss the attribute name
    display: { "Load Balancer": "true" },
    displayOrder: 1,
    canHide: true,
    displayLabel: "Has Route 53",
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "tags",
    display: "false",
  },
  {
    column: "host",
    display: "false",
  },
  {
    column: "region",
    display: "false",
  },
  {
    column: "deleted",
    display: "false",
  },
  {
    column: "hasSecondaryBackups",
    display: "false",
  },
  {
    column: "targetGroupViewModelList",
    display: "false",
  },
  {
    column: "metadata",
    display: "false",
  },
];
const S3Buckets = [
  {
    column: "id",
    display: "true",
    displayLabel: "Bucket Name",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "tags",
    displayLabel: "Tags",
    display: "true",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "backupTypes",
    displayLabel: "Protection Status",
    displayOrder: 3,
    canHide: true,
    sortable: false,
    filterable: false,
    filterMode: "none",
    sortOrder: "none",
  },
  {
    column: "creationDate",
    display: "true",
    displayLabel: "Created On",
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "true", // may not require filter
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },

  {
    column: "host",
    display: "false",
  },
  {
    column: "region",
    display: "false",
  },

  {
    column: "deleted",
    display: "false",
  },
];
const Lambda = [
  {
    column: "name",
    display: "true",
    displayLabel: "Function Name",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "tags",
    displayLabel: "Tags",
    display: "true",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "arn",
    display: "true",
    displayLabel: "arn",
    displayOrder: 3,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "runtime",
    display: "true",
    displayLabel: "Runtime",
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "false",
    filterMode: "none",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "backupTypes",
    displayLabel: "Protection Status",
    display: true,
    displayOrder: 5,
    canHide: true,
    sortable: false,
    filterable: false,
    filterMode: "none",
    sortOrder: "none",
  },
  {
    column: "deleted",
    display: "false",
  },

  {
    column: "metadata",
    display: "false",
  },
];
const DynamoDB = [
  {
    column: "tableName",
    display: "true",
    displayLabel: "Table Name",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "tags",
    displayLabel: "Tags",
    display: "true",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "backupTypes",
    displayLabel: "Protection Status",
    display: true,
    displayOrder: 3,
    canHide: true,
    sortable: false,
    filterable: false,
    filterMode: "none",
    sortOrder: "none",
  },

  {
    column: "tableSize",
    display: "true",
    displayLabel: "Table Size",
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "itemCount",
    display: "true",
    displayLabel: "Item Count",
    displayOrder: 5,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "creationDateTime",
    display: "true",
    displayLabel: "Created On",
    displayOrder: 6,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "tableId",
    display: "false",
  },
  {
    column: "tableStatus",
    display: "false",
  },
];
const EFS = [
  {
    column: "id",
    display: "true",
    displayLabel: "File System ID",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "tags",
    displayLabel: "Tags",
    display: "true",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },

  {
    column: "size",
    display: "true",
    displayLabel: "Size",
    displayOrder: 3,
    canHide: true,
    sortable: "true",
    filterable: "false",
    filterMode: "none",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "encryptionKey",
    display: "true",
    displayLabel: "Encryption",
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "name",
    display: "false",
  },
  {
    column: "state",
    display: "false",
  },
];

const EKS = [
  {
    column: "name",
    display: "true",
    displayLabel: "Name",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "tags",
    displayLabel: "Tags",
    display: "true",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "version",
    display: "true",
    displayLabel: "Version",
    displayOrder: 3,
    canHide: true,
    sortable: "true",
    filterable: "false",
    filterMode: "none",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "nodegroup",
    display: "true",
    displayLabel: "Node Group",
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "backupTypes",
    displayLabel: "Protection Status",
    display: true,
    displayOrder: 5,
    canHide: true,
    sortable: false,
    filterable: false,
    filterMode: "none",
    sortOrder: "none",
  },
  {
    column: "id",
    display: "false",
  },
  {
    column: "state",
    display: "false",
  },
  {
    column: "arn",
    display: "false",
  },
];

const ECR = [
  {
    column: "name",
    display: "true",
    displayLabel: "Name",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "arn",
    display: "true",
    displayLabel: "arn",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "repositoryUri",
    display: "true",
    displayLabel: "Repository URI",
    displayOrder: 3,
    canHide: true,
    sortable: "true",
    filterable: "false",
    filterMode: "none",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "encryptionKey", // it will be kmsKeyId later
    display: "true",
    displayLabel: "Encryption",
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "backupTypes",
    displayLabel: "Protection Status",
    display: true,
    displayOrder: 5,
    canHide: true,
    sortable: false,
    filterable: false,
    filterMode: "none",
    sortOrder: "none",
  },
  {
    column: "id",
    display: "false",
  },
  {
    column: "registryId",
    display: "false",
  },
];

const FSX = [
  {
    column: "id",
    display: "true",
    displayLabel: "File System ID",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "tags",
    displayLabel: "Tags",
    display: "true",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "storageCapacity", //attribute name is size in other services
    display: { FSX: "true" },
    displayLabel: "Size",
    displayOrder: 3,
    canHide: true,
    sortable: "true",
    filterable: "false",
    filterMode: "CONTAINS",
    sortOrder: { asc: "true", desc: "true" },
  },
  {
    column: "encryptionKey",
    display: "true",
    displayLabel: "Encryption",
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: { asc: "true", desc: "true" },
  },

  {
    column: "type",
    display: "false",
  },
  {
    column: "version",
    display: "false",
  },
  {
    column: "status",
    display: "false",
  },

  {
    column: "backupTypes",
    display: "false",
  },
];

// Backup Groups
const BackUpGroup = [
    
];
// Job Monitoring
const JobMonitoring = [
  {
    column: "command",
    display: "true",
    displayLabel: "Command",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "message",
    display: "true",
    displayLabel: "Message",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: null,
  },
  {
    column: "group_name",
    display: "true",
    displayLabel: "Backup Group",
    displayOrder: 3,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "result",
    display: "true",
    displayLabel: "Result",
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "created_on",
    display: "true",
    displayLabel: "Start Time",
    displayOrder: 5,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: null,
  },
  {
    column: "changed_on",
    display: "true",
    displayLabel: "Completed Time",
    displayOrder: 6,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: null,
  },
  {
    column: "job_id",
    display: "false",
  },
  {
    column: "application",
    display: "false",
  },
  {
    column: "parameters",
    display: "false",
  },
  {
    column: "source_host",
    display: "false",
  },
  {
    column: "destination_host",
    display: "false",
  },
  {
    column: "created_by",
    display: "false",
  },

  {
    column: "status",
    display: "false",
  },
  {
    column: "is_fetched",
    display: "false",
  },

  {
    column: "progress_in_percentage",
    display: "false",
  },
  {
    column: "log",
    display: "false",
  },
  {
    column: "commandDetails",
    display: "false",
  },
  {
    column: "group_identifier",
    display: "false",
  },

  {
    column: "active",
    display: "false",
  },
  {
    column: "created",
    display: "false",
  },
];

//Reports
const Reports = [
  {
    column: "reportName",
    display: "true",
    displayLabel: "Report Name",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "CONTAINS",
    sortOrder: null,
  },
  {
    column: "creationTime",
    display: "true",
    displayLabel: "Creation Time",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "createdBy",
    display: "true",
    displayLabel: "Created By",
    displayOrder: 3,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },

  {
    column: "message",
    display: "true",
    displayLabel: "Message",
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },

  {
    column: "request",
    display: "true",
    displayLabel: "Request",
    displayOrder: 5,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "reportStatus",
    display: "true",
    displayLabel: "Report Status",
    displayOrder: 6,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "downloadableName",
    display: "false",
  },
];

// Scheduled Reports
const ScheduledReports = [
  {
    column: "id",
    display: "false",
    displayLabel: "",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "groupName",
    display: "false",
    displayLabel: "",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "command",
    display: "false",
    displayLabel: "",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "application",
    display: "false",
    displayLabel: "",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "parameters.reportName",
    display: "true",
    displayLabel: "Report Type",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "frequency",
    display: "true",
    displayLabel: "Duration",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "interval",
    display: "false",
    displayLabel: "",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "startsAt",
    display: "true",
    displayLabel: "Start Date",
    displayOrder: 3,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "endsAt",
    display: "false",
    displayLabel: "",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "nextFireTime",
    display: "true",
    displayLabel: "Next Run Date",
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "lastFireTime",
    display: "false",
    displayLabel: "",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "enabled",
    display: "false",
    displayLabel: "",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "deleted",
    display: "false",
    displayLabel: "",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
];
// Pending Approvals
const PendingApprovals = [
  {
    column: "command",
    display: "true",
    displayLabel: "Command",
    displayOrder: 1,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "groupName",
    display: "true",
    displayLabel: "Backup Group",
    displayOrder: 2,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },

  {
    column: "requestedBy",
    display: "true",
    displayLabel: "Requested User",
    displayOrder: 3,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "approvedBy",
    display: "true",
    displayLabel: "Approver",
    displayOrder: 4,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "status",
    display: "true",
    displayLabel: "Status",
    displayOrder: 5,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },

  {
    column: "requestedTime",
    display: "true",
    displayLabel: "Requested Time",
    displayOrder: 6,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },
  {
    column: "approvedTime",
    display: "true",
    displayLabel: "Approved-Denied Time",
    displayOrder: 7,
    canHide: true,
    sortable: "true",
    filterable: "true",
    filterMode: "SELECT",
    sortOrder: null,
  },

  {
    column: "denialReason",
    display: "false",
  },

  {
    column: "application",
    display: "false",
  },

  {
    column: "id",
    display: "false",
  },
  {
    column: "hasPermission",
    display: "false",
  },
];
