const TabulatorTable = () => {
  /* As per later discussion
    Note: Filter should be global not needed on every column instead of this we will have one global filter which will 
    --> take column Name and value
    --> FilterMode--> "TEXT"
  */
  [
    {
      column: "amiId",
      display: "false",
    },
    {
      column: "backupTypes",
      displayLabel: "Protection Status",
      display: {
        EC2: "true",
        EBS: "true",
        RDS: "true",
        "Load Balancer": "true",
        "S3 Buckers": "true",
        Lambda: "true",
        DynamoDB: "true",
        EFS: "false",
        EKS: "true",
        ECR: "true",
        FSX: "false",
      },
      sortable: false,
      filterable: false,
      filterMode: "none",
      sortOrder: null,
    },
    {
      column: "backups",
      display: "false",
    },
    {
      column: "deleted",
      display: "false",
    },
    {
      column: "amiId",
      display: "false",
    },
    {
      column: "guest",
      displayLabel: "Instance",
      display: "true",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "instanceId",
      displayLabel: "Instance ID",
      display: "true",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "instanceUsage",
      display: "false",
    },
    {
      column: "isclone",
      display: "false",
    },
    {
      column: "latestSnapshot",
      display: "false",
    },
    {
      column: "marketplaceSubscribed",
      display: "false",
    },
    {
      column: "metrics",
      display: "false",
    },
    {
      column: "powerScheduled",
      display: "true",
      displayLabel: "PowerManagement Status",
      display: {
        EC2: "true",
        EBS: "true",
        RDS: "true",
        "Load Balancer": "true",
        "S3 Buckers": "true",
        Lambda: "true",
        DynamoDB: "true",
        EFS: "false",
        EKS: "true",
        ECR: "true",
        FSX: "false",
      },
      sortable: "false",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "privateIPV4Address",
      display: "false",
    },
    {
      column: "recentBackup",
      display: "false",
    },
    {
      column: "rootDevice",
      display: "false",
    },
    {
      column: "state",
      display: "true",
      displayLabel: "Instance",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "tags",
      displayLabel: "Tags",
      display: {
        EC2: "true",
        EBS: "true",
        RDS: "true",
        "Load Balancer": "true",
        "S3 Buckers": "true",
        Lambda: "true",
        DynamoDB: "true",
        EFS: "true",
        EKS: "true",
        ECR: "false",
        FSX: "true",
      },

      display: "true",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "totalSnapshots",
      displayLabel: "Total Snapshots",
      display: {
        EC2: "true",
        RDS: "true",
        "Load Balancer": "true",
        "S3 Buckers": "true",
        Lambda: "true",
        DynamoDB: "true",
        EFS: "true",
        EKS: "true",
        ECR: "false",
        FSX: "true",
      },
      sortable: "true",
      filterable: "false",
      filterMode: "none",
      sortOrder: null,
    },
    {
      column: "latestSnapshot",
      displayLabel: "Total Snapshots",
      display: "true",
    },
    {
      column: "latestSnapshotId",
      displayLabel: "Total Snapshots",
      display: "true",
    },
    {
      column: "type",
      displayLabel: "Type",
      display: "true",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "zone",
      displayLabel: "Zone",
      display: { EC2: "true", EBS: "true", RDS: "false" },
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "name",
      displayLabel: "Instance",
      display: "true",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      // "column": name,
      displayLabel: "Volumes",
      display: "true",
      sortable: "false",
      filterable: "false",
      filterMode: "None",
      sortOrder: null,
    },
    {
      column: "state",
      displayName: "Action",
      display: "true",
      sortable: "false",
      filterable: "false",
      filterMode: "None",
      sortOrder: null,
    },

    // EBS volumes
    {
      column: "volumeid",
      displayName: "Volume",
      display: "true",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "deviceName",
      displayName: "Device Name",
      display: { EBS: "true" },
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "size",
      displayName: "Size",
      display: { EBS: "true" },
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    { column: "snapshotId" },
    { column: "name" },
    { column: "zone" },
    { column: "region" },
    { column: "deviceName" },
    { column: "size" },
    { column: "tags" },
    {
      column: "kmsKeyId",
      displayLabel: "Encryption",
      display: {
        EC2: "true",
        EBS: "true",
        RDS: "true",
        "Load Balancer": "false",
        "S3 Buckers": "false",
        Lambda: "false",
        DynamoDB: "false",
        EFS: "true",
        EKS: "false",
        ECR: "true",
        FSX: "true",
      },
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    { column: "deleted", display: "false" },
    { column: "hasSecondaryBackups", display: "false" },
    { column: "isclone", display: "false" },
    {
      column: "instanceId",
      displayLabel: "Attachment Info",
      display: { EBS: "true" },
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },

    //Load Balancer
    {
      column: "loadBalancerName",
      displayLabel: "Name",
      display: "true",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "type",
      display: "true",
      displayLabel: "Type",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },

    {
      column: "tags",
      display: "false",
    },
    {
      column: "host",
      display: "false",
    },
    {
      column: "region",
      display: "false",
    },
    {
      column: "deleted",
      display: "false",
    },
    {
      column: "hasSecondaryBackups",
      display: "false",
    },
    {
      column: "targetGroupViewModelList",
      display: "false",
    },
    {
      column: "route53", //need to discuss the attribute name
      display: { "Load Balancer": "true" },
      displayLabel: "Has Route 53",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "metadata",
      display: "false",
    },
    {
      column: "metadata.code",
      display: { "Load Balancer": "true" },
      displayLabel: "State",
    },
    {
      column: "metadata.createdTime",
      display: { "Load Balancer": "true" },
      displayLabel: "Created On",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "metadata.dnsName",
      display: { "Load Balancer": "true" },
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "metadata.vpcId",
      display: { "Load Balancer": "true" },
      displayLabel: "VPC ID",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "targetGroupViewModelList",
      displayLabel: "Targets",
      display: { "Load Balancer": "true" },
      sortable: "false",
      filterable: "false",
      filterMode: "none",
      sortOrder: null,
    },

    // S3 Buckets
    {
      column: "id",
      display: "true",
      displayLabel: "Bucket Name",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "host",
      display: "false",
    },
    {
      column: "region",
      display: "false",
    },
    {
      column: "creationDate",
      display: "true",
      displayLabel: "Created On",
      sortable: "true",
      filterable: "true", // may not require filter
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "deleted",
      display: "false",
    },

    // Lambda
    {
      column: "name",
      display: "true",
      displayLabel: "Function Name",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "runtime",
      display: "true",
      displayLabel: "Runtime",
      sortable: "true",
      filterable: "false",
      filterMode: "none",
      sortOrder: null,
    },
    {
      column: "deleted",
      display: "false",
    },
    {
      column: "arn",
      display: "true",
      displayLabel: "arn",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "metadata",
      display: "false",
    },
    {
      column: "tags",
      display: "true",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },

    // DynamoDB
    {
      column: "tableId",
      display: "false",
    },
    {
      column: "tableName",
      display: "true",
      displayLabel: "Table Name",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "tableStatus",
      display: "false",
    },
    {
      column: "tableSize",
      display: "true",
      displayLabel: "Table Size",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "itemCount",
      display: "true",
      displayLabel: "Item Count",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "creationDateTime",
      display: "true",
      displayLabel: "Created On",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    // EKS--> Elastic Kubernetes Service
    {
      column: "id",
      display: "false",
    },
    {
      column: "name",
      display: "true",
      displayLabel: "Name",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "state",
      display: "false",
    },
    {
      column: "arn",
      display: "false",
    },
    {
      column: "version",
      display: "true",
      displayLabel: "Version",
      sortable: "true",
      filterable: "false",
      filterMode: "none",
      sortOrder: null,
    },
    {
      column: "nodegroup",
      display: "true",
      displayLabel: "Node Group",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "backupTypes",
      display: "false",
    },

    // EFS --> Elastic File System
    {
      column: "id",
      display: "true",
      displayLabel: "File System ID",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "name",
      display: "false",
    },
    {
      column: "state",
      display: "false",
    },
    {
      column: "size",
      display: "true",
      displayLabel: "Size",
      sortable: "true",
      filterable: "false",
      filterMode: "none",
      sortOrder: null,
    },
    {
      column: "encryptionKey",
      display: "true",
      displayLabel: "Encryption",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },

    // ECR --> Elastic Container Registry
    {
      column: "id",
      display: "false",
    },
    {
      column: "name",
      display: "true",
      displayLabel: "Name",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "registryId",
      display: "false",
    },
    {
      column: "repositoryUri",
      display: "true",
      displayLabel: "Repository URI",
      sortable: "true",
      filterable: "false",
      filterMode: "none",
      sortOrder: null,
    },
    {
      column: "arn",
      display: "true",
      displayLabel: "arn",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "encryptionKey", // it will be kmsKeyId later
      display: "true",
      displayLabel: "Encryption",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },

    //RDS Instances
    {
      column: "awsIdentifier",
      display: "true",
      displayLabel: "DB Identifier",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "instanceProperties",
      display: "false",
    },
    {
      column: "instanceProperties[engine]",
      display: "true",
      displayLabel: "Engine",
      sortable: "true",
      filterable: "true",
      filterMode: "CONTAINS",
      sortOrder: null,
    },
    {
      column: "instanceProperties[multiAZ]",
      display: "true",
      displayLabel: "Multi-AZ",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "instanceProperties[dbInstanceStatus]",
      display: "true",
      displayLabel: "Status",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "instanceProperties[licenseModel]",
      display: "true",
      displayLabel: "License",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "instanceProperties[kmsKeyId]",
      display: "true",
      displayLabel: "Encryption",
      sortable: "true",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "tagProperties",
      display: "false",
    },
    {
      column: "region",
      display: "false",
    },
    {
      column: "snapshots",
      display: "false",
    },
    {
      column: "snapshots.snapShotCount",
      display: "true",
      displayLabel: "Total Snapshots",
      sortable: "true",
      filterable: "false",
      filterMode: "none",
      sortOrder: null,
    },
    {
      column: "powerStatus",
      display: "true",
      displayLabel: "PowerManagement Status",
      sortable: "false",
      filterable: "true",
      filterMode: "SELECT",
      sortOrder: null,
    },
    {
      column: "hasSecondaryBackups",
      display: "false",
    },
    {
      column: "deleted",
      display: "false",
    },

    // FSX 
    {
    column: 'id',
    display: 'true',
    displayLabel: 'File System ID',
    sortable: 'true',
    filterable: 'true',
    filterMode: 'CONTAINS',
    sortOrder: null
  },
  {
    column: 'storageCapacity',  //attribute name is size in other services
    display: {"FSX": "true"},
    displayLabel: 'Size',
    sortable: 'true',
    filterable: 'false',
    filterMode: 'CONTAINS',
    sortOrder: null
  },
  
  {
    column: 'type',
    display: 'false',
  },
  {
    column: 'version',
    display: 'false',
  },
  {
    column: 'status',
    display: 'false',
  },
  {
    column: 'encryptionKey',
    display: 'true',
    displayLabel: 'Encryption',
    sortable: 'true',
    filterable: 'true',
    filterMode: 'SELECT',
    sortOrder: null
  },
  {
    column: 'backupTypes',
    display: 'false',
  },
  ];
  return <div>Tabulator Table</div>;
};
export default TabulatorTable;
